# Generated by Django 6.0.5 on 2026-05-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditlog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_agentic',
            field=models.BooleanField(default=False),
        ),
    ]
