"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from the environment. Never commit a real key to source control.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Comma-separated list of hosts, e.g. "example.com,api.example.com"
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Defaults to the local SQLite file (unchanged dev behavior). For production,
# set a DATABASE_URL env var (e.g. Postgres) and it is used instead — without
# requiring any extra package just to parse it. The Postgres driver (psycopg)
# is only needed at runtime when DATABASE_URL points at Postgres.
#   DATABASE_URL="postgres://user:pass@host:5432/dbname"
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    import urllib.parse as _urlparse

    _urlparse.uses_netloc.append('postgres')
    _parsed = _urlparse.urlparse(DATABASE_URL)
    _scheme = _parsed.scheme.split('+')[0]
    _engine_map = {
        'postgres': 'django.db.backends.postgresql',
        'postgresql': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }
    _engine = _engine_map.get(_scheme)
    if not _engine:
        raise ValueError(
            f"Unsupported DATABASE_URL scheme '{_parsed.scheme}'. "
            f"Supported: postgres, postgresql, mysql, sqlite."
        )

    if _scheme == 'sqlite':
        # sqlite:////absolute/path/to/db
        _name = _parsed.path
        DATABASES = {'default': {'ENGINE': _engine, 'NAME': _name}}
    else:
        DATABASES = {
            'default': {
                'ENGINE': _engine,
                'NAME': _urlparse.unquote(_parsed.path.lstrip('/')),
                'USER': _urlparse.unquote(_parsed.username or ''),
                'PASSWORD': _urlparse.unquote(_parsed.password or ''),
                'HOST': _parsed.hostname or '',
                'PORT': str(_parsed.port or ''),
                # Persistent connections in production; harmless if unset.
                'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Destination for `python manage.py collectstatic` in production. Harmless in
# dev (the dir is simply not created until collectstatic runs).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==============================================================================
# PRODUCTION SECURITY
# ==============================================================================
if not DEBUG:
    # Trust the X-Forwarded-Proto header from a reverse proxy (nginx, ALB)
    # so Django knows the original request was HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS: tell browsers to always use HTTPS. 
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Misc hardening headers.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = 'DENY'

# These are safely un-indented so they apply globally (turning off forced SSL locally)
SECURE_SSL_REDIRECT = False 
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# ==============================================================================
# CORS CONFIGURATION
# ==============================================================================
# SECURITY WARNING: never allow all origins in production.
# Provide an explicit allowlist via the CORS_ALLOWED_ORIGINS env var
# (comma-separated), e.g. "http://localhost:3000,https://app.flowzint.com".
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Permissive only in local development
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000'
    ).split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

# Trust the same origins for CSRF (Django 4+ requires scheme).
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================

# Redis broker URL to handle message queues (DB 0 = task queue).
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Store task results and states in Redis on a SEPARATE DB (DB 1 = results)
# to isolate the result keyspace from the broker queue keyspace.
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# Standardize timezone to match Django's TIME_ZONE setting
CELERY_TIMEZONE = TIME_ZONE

# (Optional) Helpful configuration for robust background tasks
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minute hard limit for long document embeddings
# Keep task results around long enough for the frontend to poll status.
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# ==============================================================================
# LOGGING
# ==============================================================================
# Console logging so the orchestration layer (api.services.ai_service) and
# app code surface their logger.info / logger.exception output. Level is
# controlled by the LOG_LEVEL env var (default INFO; use DEBUG for verbose).
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Application loggers — emit at the configured level.
        'api': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
